# Generated by Django 4.2.16 on 2024-10-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateCoachGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingmanagement.coach')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingmanagement.group')),
            ],
        ),
        migrations.CreateModel(
            name='AssociateAthleteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingmanagement.athlete')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingmanagement.group')),
            ],
        ),
    ]
